### ISSUE TITLE
Add upload field

### ISSUE THREAD

**Issue by JessChowdhury** [payloadcms/plugin-form-builder#46]
Feature request from [discord](https://discord.com/channels/967097582721572934/1060284929583353946) to add a new `upload` option to the form builder fields

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
