### ISSUE TITLE
Add documentation about how to create form submissions + a bug

### ISSUE THREAD

**Issue by karirogg** [payloadcms/plugin-form-builder#48]
As of now, one has to dig pretty deep to figure out how to post to the form-submissions endpoint (I had to watch a 15 minute Youtube video that did not fully explain it). There even was no information that you had to post to that endpoint in the docs. 

I suggest some information about the endpoint and how it is called is added to the README file in this repository.

I noticed one small bug in form submitting when trying to figure out how to post to the endpoint. If the post request is of the form:
```
{
    "form": <form-id-here>,
    "submissionData": {}
}
```
the API creates an empty form submission, even if I have required fields in the form.

Hope this helps!

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
