### ISSUE TITLE
Document Front End Implementation

### ISSUE THREAD

**Issue by denolfe** [payloadcms/plugin-form-builder#51]
The [blog post](https://payloadcms.com/blog/create-custom-forms-with-the-official-form-builder-plugin) goes into detail about the front end implementation for calling the endpoint. 

This is not addressed in the README. One user was slightly confused because they were figuring out the endpoints on their own.

Likely can move over the section from the blog post directly into the readme.

**Comment by roguesherlock** [comment]
Haha I was just looking for this information! Like I didn't find it in the docs nor in the readme and I was just confused like how/where to actually submit the form???
Thanks for link!

P.S. love payload so far. It's really neat.

**Comment by leikoilja** [comment]
documentation would be nice. what i had to do is to adapt this example:
https://github.com/payloadcms/payload/tree/master/examples/form-builder/
into my code base. Works great, but requires understanding on how things work and tie together

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
