### ISSUE TITLE
How to use it with @payloadcms/next-payload ?

### ISSUE THREAD

**Issue by roguesherlock** [payloadcms/plugin-form-builder#55]
I currently have this quick and dirty way to do this but I'm not sure if it's correct,

actions.ts
```ts
"use server"

// import { revalidatePath } from "next/cache"
import { getPayloadClient } from "@payload/payloadClient"

import { FormDataSchema, type FormDataSchemaType } from "./schema"

export async function saveForm(data: FormDataSchemaType) {
  const payload = await getPayloadClient()
  try {
    await payload.create({
      collection: "form-submissions",
      data: FormDataSchema.parse(data),
    })
    return [true, ""]
  } catch (e) {
    console.log(e)
    return [false, JSON.stringify(e)]
  }
}
```

schema.ts
```ts
import { z } from "zod"

export const FormDataSchema = z.object({
  form: z.string(),
  submissionData: z
    .object({
      field: z.string(),
      value: z.unknown(),
    })
    .array(),
})
export type FormDataSchemaType = z.infer<typeof FormDataSchema>

```

**Comment by IAmNatch** [comment]
This will definitely work. 

One thing to note is ["Currently, if a route uses a Server Action, it is required to render dynamically"](https://nextjs.org/docs/app/building-your-application/rendering/server-components#server-rendering-strategies). If you'd prefer to have static or revalidated static pages, instead of dynamic, you can use a fetch (or graphQL) request to your payload API.

 You can see an example of this [here.](https://github.com/payloadcms/payload/blob/master/examples/form-builder/nextjs/components/Blocks/Form/index.tsx#L62-L127)

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. Please refer to [this open discussion](https://github.com/payloadcms/payload/discussions/4466) for more details and to continue the conversation. Or free free to [open a new discussion](https://github.com/payloadcms/payload/discussions) around this, or even [hop on our Discord](https://discord.com/invite/payload) and get help there.
