### ISSUE TITLE
Feature request: support custom defaultColumns for Form Submissions collection

### ISSUE THREAD

**Issue by leikoilja** [payloadcms/plugin-form-builder#56]
I would like to be able to set what columns the form submission collection must have.

For example, i have a registration for with a field `email` and would like to display it here:
![image](https://github.com/payloadcms/plugin-form-builder/assets/10655107/715c1d9e-8242-4abc-a807-49104eb6f1e8)

but simply adding:
```
      formSubmissionOverrides: {
        admin: {
          defaultColumns: ['email'],
          useAsTitle: 'email',
        },
      },
```
does not work because form submission db document is stored as:
![image](https://github.com/payloadcms/plugin-form-builder/assets/10655107/789205ef-ccbe-4331-9801-d7b43c8a4d9a)

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
