### ISSUE TITLE
Feature Request: select multiple support

### ISSUE THREAD

**Issue by dominikzogg** [payloadcms/plugin-form-builder#58]
Would be great if there is multiple select support.

```html
<select name="cars" id="cars" multiple>
  <option value="volvo">Volvo</option>
  <option value="saab">Saab</option>
  <option value="opel">Opel</option>
  <option value="audi">Audi</option>
</select>
```

**Comment by dominikzogg** [comment]
I guess for very basic support this would already be enough: https://github.com/payloadcms/plugin-form-builder/pull/59

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
