### ISSUE TITLE
Field input type hidden

### ISSUE THREAD

**Issue by matteo-naif** [payloadcms/plugin-form-builder#70]
Hello, I need an input type hidden but I can't find it in the default configuration. 
Can you explain me how can I implement it?

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
