### ISSUE TITLE
Grouping fields?

### ISSUE THREAD

**Issue by kensongzhu** [payloadcms/plugin-form-builder#74]
Is there any recommended way to group fields? 

In my use case, I have a giant form, whoses fields on the frontend are seperated into groups, e.g. either rendered as tabs or steppers.   Currently I have to define multiple forms and then merge it into one on the frontend.   Just wondering if there is a better approach to acchieve this?

**Comment by jacobsfletch** [comment]
This plugin is now being maintained in the [Packages Directory](https://github.com/payloadcms/payload/tree/main/packages/plugin-form-builder) of the [Payload Monorepo](https://github.com/payloadcms/payload). This repo will soon be archived and all open issues including this one will be closed. This issue has already been added to [this open discussion](https://github.com/payloadcms/payload/discussions/4466), though, so that it will not get lost. Please refer to that discussion for more details and to continue the conversation.
